from .simple_moving_average import simple_moving_average
simple_moving_average = simple_moving_average

from .exponentially_weighted_moving_average import exponentially_weighted_moving_average
exponentially_weighted_moving_average = exponentially_weighted_moving_average
